#!/bin/bash
# This is intended to copy one table from one cluster to another copnsidering the folloiwing
# * Source (SRC) and Target (TGT) databases can BOTH be accessed from the same machine
# * Authentication mechanism is already setup 

SRC_JDBC='jdbc:hive2://c1402-node2.coelab.cloudera.com:2181,c1402-node3.coelab.cloudera.com:2181,c1402-node4.coelab.cloudera.com:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2-interactive'
SRC_DB='source'
TGT_JDBC='jdbc:hive2://c1402-node2.coelab.cloudera.com:2181,c1402-node3.coelab.cloudera.com:2181,c1402-node4.coelab.cloudera.com:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2-interactive'
TGT_DB='target'


tables=$(beeline -u "${SRC_JDBC}" --outputformat=dsv --silent=true --showHeader=false -e "USE ${SRC_DB}; SHOW TABLES;")
[ -z "${tables}" ] && echo "ERROR: No tables returned for DB: ${SRC_DB}" && exit 1
echo "USE ${SRC_DB};" > describe.hql
for tbl in ${tables}; do
    echo "SELECT \"--- OBJECT:${tbl}:---\"; SHOW CREATE TABLE ${tbl}; SELECT \"--- DESCRIBE FORMATTED ---\"; DESCRIBE FORMATTED ${tbl}; SELECT \"+++ OBJECT:${tbl}:+++\";"
done >> describe.hql
beeline -u "${SRC_JDBC}" --outputformat=dsv --silent=true --showHeader=false -f describe.hql > objects.dat

