#!/bin/bash
# Assumes CentOS 7.2 to setup GNOME desktop with VNC

sudo yum -y groupinstall "GNOME Desktop"
sudo yum -y install tigervnc-server
sudo cp /lib/systemd/system/vncserver\@.service /etc/systemd/system/vncserver\@:1.service
sudo sed -i 's/<USER>/automaton/g' /etc/systemd/system/vncserver@:1.service
vncserver << EOF
cassandra
cassandra
EOF
sudo systemctl daemon-reload
sudo systemctl enable vncserver@:1.service
sudo systemctl start vncserver@:1.service
wget http://chrome.richardlloyd.org.uk/install_chrome.sh
chmod u+x install_chrome.sh
sudo ./install_chrome.sh
#
# CTOOL - needs the machine to be authorized
#
sudo yum -y install screen
sudo yum -y install xsel
sudo pip install virtualenv 
virtualenv -p `which python2` my-ctool-env
. my-ctool-env/bin/activate
#If errors out...
#virtualenv --clear my-ctool-env
pip install git+ssh://git@github.com/riptano/ctool.git@master#egg=automaton
#If upgrading
#pip install --upgrade git+ssh://git@github.com/riptano/ctool.git@master#egg=automaton
#Done, setup $HOME/.automaton.conf
#EOF
