#!/bin/bash
# Assumes CentOS 7.2 to setup GNOME desktop with VNC

#
# VNC Desktop install
#
sudo yum -y groupinstall "GNOME Desktop"
sudo yum -y install tigervnc-server
sudo cp /lib/systemd/system/vncserver\@.service /etc/systemd/system/vncserver\@:1.service
sudo sed -i 's/<USER>/automaton/g' /etc/systemd/system/vncserver@:1.service
vncserver << EOF
cassandra
cassandra
EOF
sudo xrandr --newmode "2560x1440_60.00"  312.25  2560 2752 3024 3488  1440 1443 1448 1493 -hsync +vsync
sudo xrandr --addmode VNC-0 "2560x1440_60.00"
sudo systemctl daemon-reload
sudo systemctl enable vncserver@:1.service
sudo systemctl start vncserver@:1.service
#
# Chrome seems to be now installed by default
#
#wget http://chrome.richardlloyd.org.uk/install_chrome.sh
#chmod u+x install_chrome.sh
#sudo ./install_chrome.sh
#
# CTOOL - needs the machine to be authorized or github install is not going to work
#
sudo yum -y install screen
sudo yum -y install xsel
sudo pip install virtualenv 
virtualenv -p `which python2` ctool-env
. ctool-env/bin/activate
# If errors out...
# virtualenv --clear ctool-env
pip install git+ssh://git@github.com/riptano/ctool.git@master#egg=automaton
# If upgrading
# pip install --upgrade git+ssh://git@github.com/riptano/ctool.git@master#egg=automaton
#
# Done, setup $HOME/.automaton.conf
#
#EOF
